### ISSUE TITLE
Warn if page does not have SSL/TLS

### ISSUE THREAD

**Issue by scienceguru1** [minewrath/MarketExpress#5]
Feature: big warning if page does not have SSL/TLS (or if it's not valid). This way test sites not using it can just ignore, but if not it's implemented in a production site, it will warn the user (maybe with a link to a page saying what it does and does not mean very clearly marked, that also states even with SSL/TLS nothing is perfect, just that this is less (trying to make a case to protect the server owner from hatred from players here a little)). Also recommend not giving an option to disable, any customer should be aware that there is a risk in my opinion.

**Comment by Dylan3304** [comment]
Defiantly, I'll lock the script if SSL is not found. I might be able to do this with $_SERVER!
